version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "12:00"
  open-pull-requests-limit: 10
  reviewers:
  - fabrice404
  assignees:
  - fabrice404
