version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  commit-message:
    prefix: "npm"
    include: "scope"
  groups:
    dependencies-patch-and-minor:
      dependency-type: development
      update-types:
        - minor
        - patch
  open-pull-requests-limit: 20
  reviewers:
  - fabrice404
  assignees:
  - fabrice404
